sonar.organization=bemontoya
sonar.projectKey=devops-node-app
sonar.projectName=devops-node-app
sonar.projectVersion=1.0.0
 
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info