name: DevOps CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-quality:
    name: Pruebas y Control de Calidad Estricto
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configurar Entorno de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependencias del Microservicio
        run: npm install

      - name: Ejecutar Pruebas Unitarias y Cobertura
        run: npm test 

      - name: Escaneo de Cumplimiento Normativo con SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}